language: d
d:
    - dmd-2.071.2
    - dmd
    - ldc-1.1.0

os:
    - linux

sudo: required
group: edge
dist: trusty

notifications:
    email: false

git:
    depth: 1

branches:
    only:
        - master

script: dub test
